#!/bin/bash

sudo curl -L --output /usr/bin/rpi-update https://raw.githubusercontent.com/Hexxeh/rpi-update/master/rpi-update && sudo chmod +x /usr/bin/rpi-update
sudo REPO_URI=https://github.com/notro/rpi-firmware rpi-update





sudo rm /boot/kernel.img.bak -r
sudo mv /boot/kernel.img /boot/kernel.img.bak

sudo cp kernel.img /boot/

sudo reboot
